version: '3'

services:
  server:
    build:
      context: ./server
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
    container_name: app_server
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/www:/home/serveruser/www:delegated
    depends_on:
      - db
      - fpm
    networks:
      app_net:
        aliases:
          - server
  fpm:
    build:
      context: ./fpm
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
    container_name: app_fpm
    restart: always
    volumes:
      - ./data/www:/home/serveruser/www:delegated
    networks:
      app_net:
  db:
    image: mariadb:10.4
    container_name: app_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      app_net:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PHP_UPLOAD_MAX_FILESIZE: 67108864
    networks:
      app_net:
networks:
  app_net:
volumes:
  db-data:
